apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app-container
          image: europe-west9-docker.pkg.dev/gcr-deployment-project/gcpu-hackathon-repo/my-app-image:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/secrets/key.json"
          volumeMounts:
            - name: firestore-key-volume
              mountPath: "/secrets"
              readOnly: true
      volumes:
        - name: firestore-key-volume
          secret:
            secretName: firestore-key
