apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment # Nom de votre déploiement
  labels:
    app: my-app
spec:
  replicas: 3 # Nombre de réplicas
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app-container
          image: gcr.io/your-project-id/your-image:latest # Remplacez par votre image Docker
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
