apiVersion: apps/v1
kind: Deployment
metadata:
  name: keyflow-api-deployment
  labels:
    app: keyflow-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: keyflow-api
  template:
    metadata:
      labels:
        app: keyflow-api
    spec:
      containers:
        - name: keyflow-api-container
          image: keyflow-api
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/secrets/key.json"
          volumeMounts:
            - name: firestore-key-volume
              mountPath: "/secrets"
              readOnly: true
      volumes:
        - name: firestore-key-volume
          secret:
            secretName: firestore-key
