import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import React from "react";
import {SidebarInset, SidebarProvider, SidebarTrigger} from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import {SessionProvider} from "next-auth/react";
import {ThemeProvider} from "next-themes";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html
          lang="en"
          // `next-themes` injects an extra classname to the body element to avoid
          // visual flicker before hydration. Hence the `suppressHydrationWarning`
          // prop is necessary to avoid the React hydration mismatch warning.
          // https://github.com/pacocoursey/next-themes?tab=readme-ov-file#with-app
          suppressHydrationWarning
      >
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SessionProvider>
            {children}
        </SessionProvider>
        </body>
      </html>
  );
}
