name: 'Build and Deploy KeyFlow-refresh to GKE'

on:
  push:
    branches:
      - main
    paths:
      - 'KeyFlow/keyflow-refresh/**'
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  GAR_LOCATION: ${{ secrets.GAR_LOCATION }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}
  DEPLOYMENT_NAME: ${{ secrets.KEYFLOW_REFRESH_DEPLOYMENT_NAME }}
  REPOSITORY: ${{ secrets.REPOSITORY }}
  IMAGE: ${{ secrets.IMAGE_KEYFLOW_REFRESH }}
  WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
  FIRESTORE_KEY: ${{ secrets.FIRESTORE_KEY }}

jobs:
  setup-build-publish-deploy-refresh:
    name: 'Setup, Build, Publish, and Deploy KeyFlow-Refresh'
    runs-on: 'ubuntu-latest'
    environment: 'production'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@f112390a2df9932162083945e46d439060d66ec2' # google-github-actions/auth@v2
        with:
          workload_identity_provider: '${{ env.WORKLOAD_IDENTITY_PROVIDER }}'

      - name: 'Docker Auth'
        uses: 'docker/login-action@v3'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.auth_token }}'
          registry: '${{ env.GAR_LOCATION }}-docker.pkg.dev'

      - name: 'Set up GKE credentials'
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: projects/gcr-deployment-project/locations/europe-west9-c/clusters/my-cluster

      - name: 'Build and push Docker container for KeyFlow-Refresh'
        run: |-
          DOCKER_TAG_REFRESH="${GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE}:${GITHUB_SHA}"

          docker build \
            --tag "${DOCKER_TAG_REFRESH}" \
            KeyFlow/keyflow-refresh

          docker push "${DOCKER_TAG_REFRESH}"

      - name: 'Set up Kustomize'
        run: |-
          curl -sfLo kustomize.tar.gz https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv5.4.3/kustomize_v5.4.3_linux_amd64.tar.gz
          tar -xzf kustomize.tar.gz
          chmod u+x ./kustomize

      - name: 'Deploy KeyFlow-Refresh to GKE'
        run: |-
          # ./kustomize edit set image $GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/keyflow-refresh:$GITHUB_SHA
          ./kustomize build KeyFlow/keyflow-refresh | kubectl apply -f -
          kubectl rollout status deployment/$DEPLOYMENT_NAME_REFRESH

